# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Дизайн-культура
description: Гайды и&nbsp;рекомендации для&nbsp;дизайна продуктов АНО&nbsp;«Инфокультура»
email: infoculture@infoculture.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://infoculture.github.io/design-culture" # the base hostname & protocol for your site, e.g. http://example.com
host: 0.0.0.0

author: Павел Медников
author_url: https://pavelmednikov.com

company: АНО «Информационная культура»
company_url: https://infoculture.ru
company_mail: infoculture@infoculture.ru
company_phone: +7 499 500-96-58

# twitter_username: tomatoesaurus
# telegram_username: tomatoesaurus
# behance_username: mednikov
# github_username: Mednikov
# dribbble_username: mednikov
# linkedin_username: mednikov

collections:
  logo:
    title: Логотипы
    position: 1
  color:
    title: Палитра
    position: 2
  grid:
    title: Сетка
    position: 3
  typo:
    title: Типографика
    position: 4
  animation:
    title: Анимация
    position: 5
    disabled: true
  icon:
    title: Иконки
    position: 6
    disabled: true
  write:
    title: Редполитика
    position: 7
    disabled: true
  patterns:
    title: Паттерны
    position: 8
  resources:
    title: Ресурсы
    position: 10

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
